
const qaObject = {
    "Niyə bu proqrama müraciət edirsiniz?": "Təqaüd proqramı ilə öz şəxsi inkişafımı və yeni imkanlarımı genişləndirmək istəyirəm. Bu proqram mənim təhsil, təcrübə və məlumatlarımda inkişaf etmək və yeni bacarıqlar əldə etmək üçün bir şansdır." ,
    "Dəyərləriniz nələrdir? Həyatda qərar verəndə nələrə əsasən qərar verirsiniz?": "Dürüstlük, empatiya və məntiqlilik. Həyatda qərar verərkən,  öz şəxsi dəyərlərimə, təcrübələrimə və məlumatlarıma əsaslanıram. ",
    "Sizcə, bu proqrama seçilən namizəd hansı xüsusiyyətlərə sahib olmalıdır?": "Programa namizəd seçilmiş tələbələr üçün güclü iş etikası, uyğunlaşma qabiliyyəti və komandada işləyə bilmək bacarığı, fərdi və iş təcrübələrini uyğunlaşdırmaq və başqa insanlarla birgə işləmək bacarığı, komanda effektivliyini təmin etmək kimi xüsusiyyətlər kritik vəsitələrdir." ,
    "Bu xüsusiyyətlərdən hansını Siz özünüzdə yetərli hesab etmirsiniz və daha da çox inkişaf etdirmək istəyirsiniz?": "Natiqlik və liderlik bacarıqlarını özümə daha da inkişaf etdirmək istəyirəm. Bu xüsusiyyətlər mənə daha güclü bir nəzarət və təşkilatlılıq, effektiv kommunikasiya və liderlik yetərliyini vermək üçün lazımlıdır. Özümü daha da inkişaf etdirmək və bu bacarıqları daha da gücləndirmək üçün təqaüd proqramının imkanlarından faydalanmaq istəyirəm. Bu, mənə özümü daha yaxşı idarə etmək və komandada liderlik rolunu daha effektiv şəkildə ifa etmək üçün bir platform təmin edəcəkdir.",
    "Sizin üçün uğur anlayışının tərifi necədir?": "Uğuru, şəxsi məqsədlərimə çatmaq, mənim potensialımı maksimuma çıxarmaq və xoşbəxtlik və bərəkət hissi ilə dolu bir həyat sürmək kimi faktorlara əsaslanan bir anlayış olaraq tərif edirəm. Uğur mənim özümü inkişaf etdirməyə və nailiyyətlərimdən məmnunluq duymaya nail olduğum bir həyat təcrübəsi deməkdir. Bu, mənim fərdi və peşəkar hədəflərimə uyğun olaraq qoyduğum nəticələrin bir nəticəsidir. Uğur mənim içində motivasiya və rəqabət ruhunu canlandıran və həyatımın dəyərli və mənasını artıran bir amilidir.",
    "Bu günə kimi əldə etdiyiniz ən böyük uğurunuz nədir?": "Bu günə kimi əldə etdiyim ən böyük uğurum,  çətin bir layihəni tamamlamam olmuşdur. Bu layihədə müxtəlif  problemlərlə üzləşməli olmuşam, lakin səbir, təcrübə və səmərəli iş birliyi sayəsində uğurla nəticələndirmişəm. Bu uğur, özümə olan inancımı və potensialımı daha da gücləndirmiş və yeni hədəflər qoymama ilham vermişdir.",
    "Öz məqsədlərinə çatmış və uğur qazanmış bir fərd olaraq “gələcəkdəki Siz”i təsvir edin.": "Uğur qazanmış bir fərd olaraq öz sahəmdə fərq yaradan, yerinə yetirilmiş bir şəxs olacağam. Təcrübələrim və biliklərim sayəsində özümü daha da inkişaf etdirərək, məqsədlərimə çatmaq üçün sərt çalışacam. Liderlik vasitələrim və problem həll bacarıqlarım sayəsində iş dünyasında və cəmiyyətdə müsbət bir təsir qoyacağam. Mən yaradıcı, yenilikçi fikirlərimlə fərqli perspektivlər təqdim edəcəyəm və insanlara ilham verəcəyəm. Uğurlarım, özümü və digərlərini inkişaf etdirmək üçün bir güc mənbəyi olacaq və sahəmdə tanınmış, hörmət olunan bir şəxs kimi seçiləcəyim.",
    "Başqalarına motivasiya qaynağı ola biləcək bir təcrübənizi bizimlə bölüşün.": "Bir neçə ay əvvəl, bir iş proyektində işdəyərkən, çox böyük bir çətinliklə üzləşdim. Proyekt çox geniş bir məsuliyyət daşıyırdı və planlanandan çox daha çətin və müddətsiz bir hal almışdı. İşlə bağlı süniyyətlərlə və məsuliyyətsizliklərlə üzləşmək, motivasiyamı çox məhdudiyyətlərə sürükləyirdi. Mənim üçün əsas məqsəd, bu çətinliklərin üstəsindən gəlmək və inkişaf etmək idi. Mən hər gün özümü daha da gücləndirdim, yeni biliklər əldə etdim və problemləri həll etmək üçün yaratıcı yollar tapmağa çalışdım. Hətta çətinliklərdən və uğursuzluqlardan dərslər götürdüm və onları yenidən yoxlamaq üçün səhvə düşmədim.",
    "Bu günə kimi həll etdiyiniz ən böyük problem, çətinliyi təsvir edin. Öhdəsindən necə gəldiniz?": "Son zamanlarda üstesində gəlmək üçün mübarizə verdiyim ən böyük zorluq, bir iş yerindəki yoğun stresli və sıxlıq dövrü olmuşdur. İşimlə bağlı çoxlu və mürəkkəb məsələlərlə üzləşdim və bu durum məni çətinliklərə sürüklədi. Bu problemləri həll etmək üçün, birincisi, stresləri idarə edə bilmək üçün zəmanətli təcrübələrimə və özümə inancıma dayanmaq oldu. Həmçinin, iş təlimatları və məqsədlərə daha sıx bağlı qalmaq üçün bir plan təyin etdim və bu planı nizamlı şəkildə izləməyə çalışdım.",
    "Gələcək planlarınız nədir? Növbəti 1-3 il ərzində ən çox hansı məqsədə nail olmaq istəyirsiniz?": "Gələcək planlarımdan biri yeni bacarıqlar əldə etmək və karyeramda irəliləməkdir. Növbəti 3 il ərzində məqsədim, sahəmdə mövcud bilik və bacarıqlarımı genişləndirmək üçün fəaliyyətlərdə iştirak etmək və təlimlər almaqdır. Həm texniki, həm də liderlik və idarəetmə bacarıqlarında inkişaf etmək istəyirəm. Bu, mənim karyeramda daha yüksək və məmnun edici layihələrə rəhbərlik etməyə, öz potensialımı maksimuma çıxarmağa və nəticələrimi artırmağa kömək edəcəkdir. Həm özümə, həm də şirkətimə dəyər əlavə etməyə çalışacağam.",
    "Hobbiləriniz (maraqlarınız) nədir? Boş vaxtınızı necə dəyərləndirməyə üstünlük verirsiniz?": "Hobim kompüterlərlə işləmək və proqramlaşdırmadır. Boş vaxtımda yeni texnologiyaları izləmək, proqram tərtib etmək və kompüter oyunları oynamaq kimi aktivitələrlə məşğul oluram. Ayrıca, yeni proqramlaşdırma dilləri və texnologiyaları öyrənmək üçün online mənbələrdən də istifadə edirəm. Həmçinin, oxumağı və məlumat toplamağı sevirəm. Texnologiya, innovasiyalar və elmi məqalələr barədə oxumaq, mənə yenilikləri izləmək və öyrənmək imkanı verir. Sosial media platformalarında relevant məlumatları izləyirəm və bu məlumatları digərləri ilə paylaşmaq, müzakirə etmək üçün forumlara və onlayn topluluğlara daxil oluram. Boş vaxtımda dostlarlımla bir araya gəlmək, müsahibələr dinləmək və yeni insanlarla tanış olmaq da özümə yaxşı gəlir. Fiziki fəaliyyətlər, gəzinti, idman və təbiət ilə bağlı aktivitələr də zamanımı dəyərləndirmək üçün seçdiyim şeylərdəndir.",
    "Rol modeli (nümunə) olaraq gördüyünüz şəxs kimdir? Niyə bu şəxsi seçdiniz?": "Yenilikçi düşüncə tərzinə görə ilham aldığım insanlardan biri Elon Muskdır.                                  ",
    "Cəmiyyətə necə faydalı olursunuz və ya olmağı düşünürsünüz?": "Cəmiyyətə faydalı olmaq üçün fərqli yollarla töhfə verməyə çalışıram. Birinci olaraq, mən şəxsi və peşəkar təcrübələrimi başkaları ilə bölüşmək, məsləhətlər vermək və mentorluq etmək kimi şəxsi inkişaf və karyera məqsədləri üzrə yardım etmək üçün fəaliyyət göstərirəm. Həmçinin, mən dərc olunan məqalələr, blog yazıları, və ya texnologiya və innovasiyalar barədə paylaşımlar vasitəsilə məlumat paylaşımı edirəm. Bu, insanlara yeni biliklər verməyə, məqbul praktikaları yaymağa və onların dəyişən dünyadakı dəyişikliklərə ayak uydurmağa kömək edir. Həmçinin, səmərəli şəkildə işləyən şirkətlərdə çalışaraq, yenilikçilik və texnologiyalarda irəliləməyə töhfə verməyə çalışıram. Bu, yeni istəhdam yaratmaq və cəmiyyətə maddi və mədəni dəyərlər əlavə etmək deməkdir.",
    "Tələbələr üçün təqaüd və inkişaf proqramı təşkil etmək Sizə tapşırılarsa, necə bir proqram formalaşdırardınız?": "Tələbələr üçün təqaüd və inkişaf proqramının formalaşdırılması üçün ilkin olaraq onların məqsəd və hədəflərinin müəyyən edilməsi ilə  başlayardım. Bu, tələbələrin həyatlarında, təhsilində və karyera inkişafında nəyi hədəfləmələri və nələrə nail olmağı arzuladıqlarını anlamağımıza köməklik edəcək. Daha sonra iştirakçıların təyin edilməsi üçün proqramın hansı qrup tələbələr üçün olduğunu müəyyən etmək önəmlidir. Bu, tələbələrin akademik, sosial və mənəvi inkişafını dəstəkləyəcək və potensiallarını artıracaq bir qrup təşkil etmək deməkdir. Proqramın əsas hissələrindən biri tələbələrin təhsilini və mentorluğunu dəstəkləməkdir. Bu, tələbələrin akademik bacarıqları¬¬nı inkişaf etdirmək, biliklərini artırmaq və öz potensiallarını maksimuma çıxarmaq üçün proqram çərçivəsində müxtəlif təhsil imkanları, kurslar və mentorluq proqramları təklif etməyi daxil edir.",
}

module.exports = qaObject